### PR TITLE
Add a label to display placeholder text.

### PR DESCRIPTION
**Pull request by chapados**
This change adds a UILabel above the internalTextView,
configured to display placeholder text.  The label is
positioned such that the cursor of the textView is still
visible when the textView becomes firstResponder.

When the textView changes, the 'hidden' state of the
placeholder label is updated to show/hide the placeholder.

### CODE REVIEW

**Comment by jonasman** [comment]
great!

**Comment by hanspinckaers** [comment]
Good implementation, but I don't like that if you don't set a placeholder, the UILabel is still initialized. Maybe we could initialize the placeholder UILabel when you set the placeholder NSString from the first time.

**Comment by chapados** [comment]
Thanks for the feedback. That's a good suggestion. I will change it so that the UILabel is lazily initialized when a placeholder string is set for the first time.

**Comment by hanspinckaers** [comment]
Added another placeholder implementation.

**Pull request closed without merging**
