### PR TITLE
Update to handle deprecation with iOS 7.0 target

### PR DESCRIPTION
**Pull request by dav**

### CODE REVIEW

**Comment by hanspinckaers** [comment]
Thanks!

**Comment by nycom83** [comment]
This merge breaks the compatibility with iOS 6.x

**Comment by dav** [comment]
Huh, the #if __IPHONE_OS_VERSION_MAX_ALLOWED < 70000 doesn't work as expected with 6.x?

I admit I didn't try it (and can't right now) but didn't expect that to fail....

**Comment by nycom83** [comment]
My app supports iOS 6.x and 7.0
So, in my project, __IPHONE_OS_VERSION_MAX_ALLOWED is equal to 70000.

The following code will be compiled and executed, even on ios 6
[placeholder drawInRect:CGRectMake(8.0f, 8.0f, self.frame.size.width - 16.0f, self.frame.size.height - 16.0f)
                 withAttributes:@{NSFontAttributeName: self.font, NSForegroundColorAttributeName: placeholderColor}];

**Comment by dav** [comment]
Ah, I see. so there needs to be a runtime check. Sorry about that.

I guess either it needs to be a runtime check in addition to the compile check, or else use a pragma to disable to deprecation warning.

**Pull request merged**
